#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ def in_list(key, list):
#@  return (hasattr(data.values.tap_values.ootb_supply_chain_basic.gitops, key) and (data.values.tap_values.ootb_supply_chain_basic.gitops[key] in list) or hasattr(data.values.tap_values.ootb_supply_chain_testing.gitops, key) and (data.values.tap_values.ootb_supply_chain_testing.gitops[key] in list) or hasattr(data.values.tap_values.ootb_supply_chain_testing_scanning.gitops, key) and (data.values.tap_values.ootb_supply_chain_testing_scanning.gitops[key] in list))
#@ end
#@ if/end not in_list('ssh_secret', ['']):
---
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  annotations:
    tekton.dev/git-0: #@ "{}".format(data.values.imported.git.host)
type: kubernetes.io/basic-auth
data:
  username: #@ base64.encode(data.values.imported.git.username)
  password: #@ base64.encode(data.values.imported.git.password)
  caFile: #@ base64.encode(data.values.imported.git.caFile)
